#!/bin/sh
# This script runs 'make clean ; make -j NCORE release', which should do everything
# necessary on TRAVIS.
SDIR=$(dirname "$(readlink -f "$0")")
if [ "${SDIR}" != "$PWD" ] ; then
  echo "publish script must be run in its own directory." >&2
  exit 1
fi

if [ "$TRAVIS" != "true" ] ; then
  if [ "$1" != "-f" ] ; then
    echo "No TRAVIS detected. Use $0 -f to force running publish script." >&2
    exit 1
  fi
  echo "No TRAVIS detected, but forcing run." >&2
fi

ncore=2  # hardcode 2 threads on TRAVIS

echo -e "Cleaning"
make clean

echo -e "Building using $ncore thread(s)\n"
exec make -j $ncore release

